apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pwglsp0pa-nodejs 
  janus-idp.io/tekton: pwglsp0pa-nodejs
  backstage.io/kubernetes-id: pwglsp0pa-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pwglsp0pa-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  